version: '2'

services:
  yolo4motion:
    image: dcmartin/arm_com.github.dcmartin.open-horizon.yolo4motion:0.1.5
    restart: unless-stopped
    network_mode: host
    container_name: yolo4motion
    environment:
      - SERVICE_LABEL=yolo4motion
      - SERVICE_VERSION=0.1.5
      - SERVICE_PORT=4662
      - MQTT_HOST=192.168.1.98
      - MQTT_PORT=1883
      - MQTT_USERNAME=username
      - MQTT_PASSWORD=password
      - MOTION_GROUP=motion
      - MOTION_CLIENT=pi44
      - YOLO4MOTION_CAMERA=+
      - YOLO4MOTION_TOPIC_EVENT=event/end
      - YOLO4MOTION_TOPIC_PAYLOAD=image/end
      - YOLO4MOTION_USE_MOCK=false
      - YOLO4MOTION_TOO_OLD=500
      - YOLO_CONFIG=tiny-v2
      - YOLO_ENTITY=all
      - YOLO_SCALE=none
      - YOLO_THRESHOLD=0.25
      - YOLO_PERIOD=60
      - LOG_LEVEL=info
      - LOGTO=/dev/stderr
      - DEBUG=false
  face4motion:
    image: dcmartin/arm_com.github.dcmartin.open-horizon.face4motion:0.0.5
    restart: unless-stopped
    network_mode: host
    container_name: face4motion
    environment:
      - SERVICE_LABEL=face4motion
      - SERVICE_VERSION=0.0.5
      - SERVICE_PORT=4662
      - MQTT_HOST=192.168.1.98
      - MQTT_PORT=1883
      - MQTT_USERNAME=username
      - MQTT_PASSWORD=password
      - MOTION_GROUP=motion
      - MOTION_CLIENT=pi44
      - FACE4MOTION_CAMERA=+
      - FACE4MOTION_TOPIC_EVENT=event/end
      - FACE4MOTION_TOPIC_PAYLOAD=image/end
      - FACE4MOTION_USE_MOCK=false
      - FACE4MOTION_TOO_OLD=500
      - FACE_COUNTRY=us
      - FACE_PATTERN=all
      - FACE_SCALE=none
      - FACE_THRESHOLD=0.25
      - FACE_PERIOD=60
      - LOG_LEVEL=info
      - LOGTO=/dev/stderr
      - DEBUG=false
  alpr4motion:
    image: dcmartin/arm_com.github.dcmartin.open-horizon.alpr4motion:0.0.5
    restart: unless-stopped
    network_mode: host
    container_name: alpr4motion
    environment:
      - SERVICE_LABEL=alpr4motion
      - SERVICE_VERSION=0.0.5
      - SERVICE_PORT=4663
      - MQTT_HOST=192.168.1.98
      - MQTT_PORT=1883
      - MQTT_USERNAME=username
      - MQTT_PASSWORD=password
      - MOTION_GROUP=motion
      - MOTION_CLIENT=pi44
      - ALPR4MOTION_CAMERA=+
      - ALPR4MOTION_TOPIC_EVENT=event/end
      - ALPR4MOTION_TOPIC_PAYLOAD=image/end
      - ALPR4MOTION_USE_MOCK=false
      - ALPR4MOTION_TOO_OLD=500
      - ALPR_COUNTRY=us
      - ALPR_PATTERN=all
      - ALPR_SCALE=none
      - ALPR_TOPN=10
      - ALPR_PERIOD=60
      - LOG_LEVEL=info
      - LOGTO=/dev/stderr
      - DEBUG=false
