###
## homeassistant/sensor/motion/reload.yaml
###

- platform: template
  sensors:
    motion_reload_repository:
      value_template: >-
        {% set s = states('input_text.motion_reload_repository') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
          {{ s }}
        {% else %}null{% endif %}
