###
# homeassistant/sensor/motion/router_name.yaml
###

- platform: template
  sensors:
    motion_router_name_array:
      friendly_name: Motion routers
      icon_template: 'mdi:web'
      value_template: >-
        [{%- for state in states.sensor if '_packets_s_received' in state.entity_id|lower and states(state.entity_id)|lower != 'unknown' -%}
          {%- if loop.first -%}{%- else -%},{%- endif -%}
          {%- set n = state.entity_id|lower -%}
          "{{- n|replace('sensor.','')|replace('_packets_s_received','') -}}"
        {%- endfor -%}]

- platform: template
  sensors:
    motion_router_name:
      friendly_name: Motion router
      icon_template: 'mdi:web'
      value_template: >-
        {% set s = states('sensor.motion_router_name_array') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {% set s = s|from_json %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' and s is iterable and s|length > 0 %}
            {{ s|first }}
          {% else %}Pending{% endif %}
        {% else %}Pending{% endif %}

- platform: template
  sensors:
    motion_router_bits_received:
      friendly_name: Bits received
      value_template: >-
        {% set s = states('sensor.motion_router_name') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ states('sensor.' + s + '_b_received') }}
        {% else %}null{% endif %}
    motion_router_bits_sent:
      friendly_name: Bit sent
      value_template: >-
        {% set s = states('sensor.motion_router_name') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ states('sensor.' + s + '_b_sent') }}
        {% else %}null{% endif %}
    motion_router_pkts_received:
      friendly_name: Packets received
      value_template: >-
        {% set s = states('sensor.motion_router_name') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ states('sensor.' + s + '_packets_received') }}
        {% else %}null{% endif %}
    motion_router_pkts_sent:
      friendly_name: Packets sent
      value_template: >-
        {% set s = states('sensor.motion_router_name') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ states('sensor.' + s + '_packets_sent') }}
        {% else %}null{% endif %}
    motion_router_kbs_received:
      friendly_name: Kbps received
      value_template: >-
        {% set s = states('sensor.motion_router_name') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ states('sensor.' + s + '_kib_s_received') }}
        {% else %}null{% endif %}
    motion_router_kbs_sent:
      friendly_name: Kps sent
      value_template: >-
        {% set s = states('sensor.motion_router_name') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ states('sensor.' + s + '_kib_s_sent') }}
        {% else %}null{% endif %}
    motion_router_pps_received:
      friendly_name: Packets received/s
      value_template: >-
        {% set s = states('sensor.motion_router_name') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ states('sensor.' + s + '_packets_s_received') }}
        {% else %}null{% endif %}
    motion_router_pps_sent:
      friendly_name: Packets sent/s
      value_template: >-
        {% set s = states('sensor.motion_router_name') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ states('sensor.' + s + '_packets_s_sent') }}
        {% else %}null{% endif %}
