###
## homeassistant/motion/sensor/shelly.yaml
###

## MQTT

# shellies/pir-bathroom/status
# {
#   "active": true,
#   "bat": 99,
#   "lux": 438,
#   "motion": false,
#   "timestamp": 1622456177,
#   "vibration": false
# }

- platform: mqtt
  name: motion_detector_shelly_status
  state_topic: shellies/+/status
  json_attributes_topic: shellies/+/status
  qos: 2
  value_template: >
    {% if value_json is defined %}True{% else %}False{% endif %}

# shellies/shellymotionsensor-60A423D3F280/announce
# {
#   "fw_ver": "20210226-072307/v1.1.0@f31e1d2b",
#   "id": "shellymotionsensor-60A423D3F280",
#   "ip": "192.168.1.224",
#   "mac": "60A423D3F280",
#   "model": "SHMOS-01",
#   "new_fw": false
# }

- platform: mqtt
  name: motion_detector_shelly_announce
  state_topic: shellies/+/announce
  json_attributes_topic: shellies/+/announce
  qos: 2
  value_template: >
    {% if value_json is defined %}True{% else %}False{% endif %}

# shellies/shellymotionsensor-60A423D3F280/info
# {
#   "bat": {
#     "value": 100,
#     "voltage": 4.171
#   },
#   "cfg_changed_cnt": 0,
#   "charger": true,
#   "cloud": {
#     "connected": false,
#     "enabled": false
#   },
#   "has_update": false,
#   "lux": {
#     "illumination": "bright",
#     "is_valid": true,
#     "value": 1027
#   },
#   "mac": "60A423D3F280",
#   "mqtt": {
#     "connected": true,
#     "enabled": true
#   },
#   "sensor": {
#     "active": true,
#     "is_valid": true,
#     "motion": false,
#     "timestamp": 1622451089,
#     "vibration": false
#   },
#   "serial": 212,
#   "time": "09:09",
#   "timestamp": -1815024272,
#   "unixtime": 1622452158,
#   "update": {
#     "beta_version": "",
#     "has_update": false,
#     "new_version": "20210226-072307/v1.1.0@f31e1d2b",
#     "old_version": "20210226-072307/v1.1.0@f31e1d2b",
#     "status": "idle"
#   },
#   "uptime": 75681,
#   "wifi_sta": {
#     "connected": true,
#     "ip": "192.168.1.224",
#     "rssi": -48,
#     "ssid": "CABIN"
#   }
# }

- platform: mqtt
  name: motion_detector_shelly_info
  state_topic: shellies/+/info
  json_attributes_topic: shellies/+/info
  qos: 2
  value_template: >
    {% if value_json is defined %}True{% else %}False{% endif %}

## REST

# curl -sSL -u 'username:password' "192.168.1.224/settings"
# {
#   "build_info": {
#     "build_id": "20210226-072307/v1.1.0@f31e1d2b",
#     "build_timestamp": "2021-02-26T07:23:07Z",
#     "build_version": "2021022607"
#   },
#   "cloud": {
#     "enabled": false
#   },
#   "coiot": {
#     "enabled": false,
#     "peer": "",
#     "update_period": 3600
#   },
#   "dark_threshold": 100,
#   "device": {
#     "hostname": "shellymotionsensor-60A423D3F280",
#     "mac": "60A423D3F280",
#     "num_outputs": 0,
#     "type": "SHMOS-01"
#   },
#   "discoverable": true,
#   "fw": "20210226-072307/v1.1.0@f31e1d2b",
#   "hwinfo": {
#     "batch_id": 0,
#     "hw_revision": "dev-prototype"
#   },
#   "lat": 37.9577,
#   "led_status_disable": true,
#   "lng": -121.29078,
#   "login": {
#     "auth_type": "basic",
#     "default_username": "admin",
#     "enabled": true,
#     "unprotected": false,
#     "username": "username"
#   },
#   "motion": {
#     "blind_time_minutes": 1,
#     "enabled": true,
#     "operating_mode": 0,
#     "pulse_count": 1,
#     "sensitivity": 50
#   },
#   "mqtt": {
#     "clean_session": true,
#     "enable": true,
#     "id": "pir-bathroom",
#     "max_qos": 0,
#     "retain": false,
#     "server": "192.168.1.40:1883",
#     "update_period": 3600,
#     "user": "username"
#   },
#   "name": "pir-bathroom",
#   "pin_code": "B-X0)>",
#   "schedule": false,
#   "schedule_rules": [],
#   "sleep_mode": {
#     "period": 60,
#     "unit": "m"
#   },
#   "sleep_time": 0,
#   "sntp": {
#     "enabled": true,
#     "server": "time.google.com"
#   },
#   "tamper_sensitivity": 2,
#   "time": "11:58",
#   "timezone": "America/Los_Angeles",
#   "twilight_threshold": 500,
#   "tz_dst": false,
#   "tz_dst_auto": true,
#   "tz_utc_offset": -25200,
#   "tzautodetect": true,
#   "wifi_ap": {
#     "enabled": false,
#     "ssid": "shellymotionsensor-60A423D3F280"
#   },
#   "wifi_sta": {
#     "dns": null,
#     "enabled": true,
#     "gw": null,
#     "ip": null,
#     "ipv4_method": "dhcp",
#     "mask": null,
#     "ssid": "CABIN"
#   }
# }

- platform: rest
  name: motion_shelly_settings
  authentication: basic
  username: "username"
  password: "password"
  scan_interval: 1800
  json_attributes:
    - build_info
    - cloud
    - coiot
    - lat
    - lng
    - led_status_disable
    - mqtt
    - name
    - motion
    - login
    - device 
    - timezone
    - wifi_ap
    - wifi_sta
  force_update: true
  resource_template: >-
    {% set s = states('sensor.motion_shelly_settings_api') %}
    {% if s|lower !='none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
      {{- s -}}
    {% else %}
      {{- 'http://192.168.1.224/settings' -}}
    {% endif %}
  value_template: >-
    {% if value_json is defined %}True{% else %}False{% endif %}

- platform: history_stats
  name: motion_detector_shelly_history_ratio_today
  entity_id: binary_sensor.motion_detector_shelly
  state: 'on'
  type: ratio
  start: >-
    {{ now().replace(hour=0).replace(minute=0).replace(second=0) }}
  end: '{{ now() }}'

- platform: history_stats
  name: motion_detector_shelly_history_count_today
  entity_id: binary_sensor.motion_detector_shelly
  state: 'on'
  type: count
  start: >-
    {{ now().replace(hour=0).replace(minute=0).replace(second=0) }}
  end: '{{ now() }}'

- platform: template
  sensors:
    motion_detector_shelly_ago:
      friendly_name: 'Shelly motion ago'
      icon_template: 'mdi:av-timer'
      unit_of_measurement: 's'
      value_template: >-
        {{ state_attr('binary_sensor.motion_detector_shelly','ago') }}

- platform: statistics
  name: motion_detector_shelly_ago_statistics
  entity_id: sensor.motion_motion_shelly_ago
  sampling_size: 1000
  max_age:
    hours: 168
