###
## homeassistant/sensor/homeassistant_url.yaml
###

- platform: template
  sensors:
    homeassistant_url:
      friendly_name: HA URL
      value_template: >-
        {%- set s = states('input_text.homeassistant_url') -%}
        {%- if s|lower != 'unknown' and s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'null' -%}
          {{- s -}}
        {%- else -%}
          {{- 'http://127.0.0.1:8123' -}}
        {%- endif -%}

- platform: rest
  name: homeassistant_version_latest
  resource: 'https://version.home-assistant.io/stable.json'
  force_update: true
  method: GET
  timeout: 5
  json_attributes:
    - channel
    - supervisor
    - homeassistant
    - hassos
    - cli
    - dns
    - audio
    - multicast
  value_template: >-
    {% if value_json is defined %}
      {{ value_json.homeassistant.default }}
    {% else %}null{% endif %}
