###
# homeassistant/binary_sensor/motion/addon_rtsp.yaml
###

- platform: template
  sensors:
    motion_addon_rtsp:
      friendly_name: 'Add-on RTSP'
      icon_template: 'mdi:web'
      attribute_templates: >-
        nmap: >-
          {% set s = state_attr('sensor.motion_addon_rtsp','rtsp') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
            {{ s.nmap }}
          {% else %}null{% endif %}
        cameras: >-
          {%- set s = state_attr('sensor.motion_addon_rtsp','rtsp') -%}
          {%- if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s != null and s|list is iterable -%}
            {{- s.devices|selectattr("code","equalto",'200')|map(attribute="ip")|list -}}
          {%- else -%}null{%- endif -%}
        count: >-
          {% set s = state_attr('sensor.motion_addon_rtsp','rtsp') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
            {% set s = s.devices %}
            {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|list is iterable %}
              {{ s|selectattr('code','==','200')|list|length }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        ago: >-
          {% set s = state_attr('sensor.motion_addon_rtsp','timestamp') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s != null %}
            {{ (utcnow().timestamp()|int - as_timestamp(s)|int)|int }}
          {% else %}null{% endif %}
      value_template: >-
        {{ is_state('sensor.motion_addon_rtsp','True') }}
