###
# homeassistant/binary_sensor/motion/person.yaml
###

- platform: template
  sensors:
    motion_person_smartphone_interactive:
      friendly_name: '👱📱'
      icon_template: 'mdi:cellphone'
      value_template: >-
        {%- set s = states('sensor.motion_person_device') -%}
        {%- if s|lower != 'none' and s|lower != 'unknown' and s|lower != 'unavailable' and s|lower != 'null' -%}
          {%- set s = states('binary_sensor.' + s + '_interactive') -%}
          {%- if s|lower != 'none' and s|lower != 'unknown' and s|lower != 'unavailable' and s|lower != 'null' -%}
            {{- s -}}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}
    motion_person_smartphone_powersave:
      friendly_name: '📱🔋'
      icon_template: 'mdi:battery-low'
      value_template: >-
        {%- set s = states('sensor.motion_person_device') -%}
        {%- if s|lower != 'none' and s|lower != 'unknown' and s|lower != 'unavailable' and s|lower != 'null' -%}
          {%- set s = states('binary_sensor.' + s + '_powersave') -%}
          {%- if s|lower != 'none' and s|lower != 'unknown' and s|lower != 'unavailable' and s|lower != 'null' -%}
            {{- s -}}
          {%- else -%}null{%- endif -%}
        {%- else -%}null{%- endif -%}
