###
## motion/binary_sensor/pose_detected.yaml
###

## pose_detected
- platform: template
  sensors:
    motion_pose_detected:
      friendly_name: POSE detected
      icon_template: 'mdi:walk'
      value_template: >-
        {% set count = state_attr('sensor.motion_event_pose','count') %}
        {% set percents = state_attr('sensor.motion_event_pose','detected') %}
        {% if count|lower != 'none' and percents|lower != 'none' and count != 'null' and percents|length > 0 %}
          {{ count|int > 0 and percents|max|int >= states('input_number.motion_pose_detected_percent')|int }}
        {% else %}false{% endif %}

- platform: template
  sensors:
    motion_pose_detected_expired:
      value_template: >-
        {{ states('sensor.motion_pose_detected_ago')|int > states('input_number.motion_pose_detected_ago')|int }}
