###
# binary_sensor/motion/shelly.yaml
###

- platform: template
  sensors:
    motion_shellies_publish:
      value_template: >-
        {% set s = states('input_boolean.motion_shellies_publish') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{- s -}}
        {% else %}true{% endif %}
    motion_shellies_occupancy:
      unique_id: motion_shellies_occupancy_all
      friendly_name: Occupancy
      device_class: 'occupancy'
      icon_template: >-
        {% if is_state('binary_sensor.motion_shellies_occupancy','on') %}
          {{- 'mdi:motion-sensor' -}}
        {% else %}
          {{- 'mdi:motion-sensor-off' -}}
        {% endif %}
      value_template: >-
        {% set s = state_attr('sensor.motion_shellies_occupancy','status') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' and s is iterable %}
          {{ s|select('==','on')|list|length > 0 }}
        {% else %}false{% endif %}
    motion_shellies_light:
      unique_id: motion_shellies_light_all
      friendly_name: Light
      device_class: 'light'
      icon_template: >-
        {% if is_state('binary_sensor.motion_shellies_light','on') %}
          {{- 'mdi:lightbulb-on-outline' -}}
        {% else %}
          {{- 'mdi:lightbulb' -}}
        {% endif %}
      value_template: >-
        {% set s = state_attr('sensor.motion_shellies_light','status') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' and s is iterable %}
          {{ s|select('==','on')|list|length > 0 }}
        {% else %}false{% endif %}
