###
# binary_sensor/motion/shelly.yaml
###

- platform: template
  sensors:
    motion_detector_shelly_announce:
      value_template: >-
        {% set s = states('input_boolean.motion_detector_shelly_announce') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{- s -}}
        {% else %}true{% endif %}
    motion_detector_shelly:
      friendly_name: Shelly motion
      device_class: 'occupancy'
      availability_template: >-
        {{ is_state_attr('sensor.motion_detector_shelly_status','active','true') }}
      icon_template: >-
        {% if is_state_attr('sensor.motion_detector_shelly_status','motion','true') %}
          {{- 'mdi:motion-sensor' -}}
        {% else %}
          {{- 'mdi:motion-sensor-off' -}}
        {% endif %}
      attribute_templates:
        vibration: >-
          {{ is_state_attr('sensor.motion_detector_shelly_status','vibration','true') }}
        active: >-
          {{ is_state_attr('sensor.motion_detector_shelly_status','active','true') }}
        lux: >-
          {{ state_attr('sensor.motion_detector_shelly_status','lux') }}
        bat: >- 
          {{ state_attr('sensor.motion_detector_shelly_status','bat') }}
        timestamp: >-
          {{ state_attr('sensor.motion_detector_shelly_status','timestamp') }}
        when: >-
          {% set s = state_attr('sensor.motion_detector_shelly_status','timestamp') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
          {% else %}Pending{% endif %}
        duration: >-
          {% if is_state_attr('sensor.motion_detector_shelly_status','motion','false') %}
            {% set s = states('sensor.motion_detector_shelly_timestamp') %}
            {% if s|lower != 'unknown' and s|lower != 'unavailable' and s|lower != 'none' and s|lower != 'null' %}
              {{ state_attr('sensor.motion_detector_shelly_status','timestamp')|int - s|int  }}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        ago: >-
          {% if is_state_attr('sensor.motion_detector_shelly_status','motion','true') %}
            {% set s = state_attr('sensor.motion_detector_shelly_status','timestamp') %}
            {% if s|lower != 'unknown' and s|lower != 'unavailable' and s|lower != 'none' and s|lower != 'null' %}
              {{ utcnow().timestamp()|int - s|int }}
            {% else %}null{% endif %}
          {% else %}
            {% set s = state_attr('binary_sensor.motion_detector_shelly','ago') %}
            {% if s|lower != 'unknown' and s|lower != 'unavailable' and s|lower != 'none' and s|lower != 'null' %}
              {{ s }}
            {% else %}null{% endif %}
          {% endif %}
      value_template: >-
        {% set s = state_attr('sensor.motion_detector_shelly_status','motion') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ s|lower == 'true' }}
        {% else %}false{% endif %}
