###
# binary_sensor/motion/shelly.yaml
###

- platform: template
  sensors:
    motion_detector_shelly:
      friendly_name: Shelly motion
      icon_template: >-
        {% if is_state_attr('sensor.motion_detector_shelly_status','motion','true') %}
          {{- 'mdi:motion-sensor' -}}
        {% else %}
          {{- 'mdi:motion-sensor-off' -}}
        {% endif %}
      attribute_templates:
        vibration: >-
          {{ is_state_attr('sensor.motion_detector_shelly_status','vibration','true') }}
        active: >-
          {{ is_state_attr('sensor.motion_detector_shelly_status','active','true') }}
        lux: >-
          {{ state_attr('sensor.motion_detector_shelly_status','lux') }}
        bat: >- 
          {{ state_attr('sensor.motion_detector_shelly_status','bat') }}
        timestamp: >-
          {{ state_attr('sensor.motion_detector_shelly_status','timestamp') }}
        when: >-
          {% set s = state_attr('sensor.motion_detector_shelly_status','timestamp') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
          {% else %}Pending{% endif %}
        ago: >-
          {% set s = state_attr('sensor.motion_detector_shelly_status','timestamp') %}
          {% if s|lower != 'unknown' and s|lower != 'unavailable' and s|lower != 'none' and s|lower != 'null' %}
            {{ now().timestamp()|int - s|int }}
          {% else %}null{% endif %}
      value_template: >-
        {% set s = state_attr('sensor.motion_detector_shelly_status','motion') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ s|lower == 'true' }}
        {% else %}Pending{% endif %}
