###
# binary_sensor/motion/shelly.yaml
###

- platform: template
  sensors:
    motion_shellies_publish:
      value_template: >-
        {{ is_state('input_boolean.motion_shellies_publish','on') }}
    motion_shellies_scan:
      value_template: >-
        {{ is_state('input_boolean.motion_shellies_scan','on') }}
    motion_shellies_publish_update:
      value_template: >-
        {{ is_state('input_boolean.motion_shellies_publish_update','on') }}
    motion_shellies_offline:
      unique_id: motion_shellies_offline
      value_template: >-
        {{ false }}

- platform: template
  sensors:
    motion_shellies_light:
      unique_id: motion_shellies_light_all
      friendly_name: Light
      device_class: 'light'
      icon_template: >-
        {% if is_state('binary_sensor.motion_shellies_light','on') %}
          {{- 'mdi:lightbulb-on-outline' -}}
        {% else %}
          {{- 'mdi:lightbulb' -}}
        {% endif %}
      value_template: >-
        {{- false -}}
    motion_shellies_light_outage:
      value_template: >-
        {{ false }}

- platform: template
  sensors:
    motion_shellies_moisture:
      unique_id: motion_shellies_moisture_all
      friendly_name: Moisture
      device_class: 'moisture'
      icon_template: >-
        {% if is_state('binary_sensor.motion_shellies_moisture','on') %}
          {{- 'mdi:water-alert' -}}
        {% else %}
          {{- 'mdi:water-outline' -}}
        {% endif %}
      value_template: >-
        {{- false -}}

- platform: template
  sensors:
    motion_shellies_gas:
      unique_id: motion_shellies_gas_all
      friendly_name: Moisture
      #device_class: 'gas'
      icon_template: >-
        {% if is_state('binary_sensor.motion_shellies_gas','on') %}
          {{- 'mdi:water-alert' -}}
        {% else %}
          {{- 'mdi:water-outline' -}}
        {% endif %}
      value_template: >-
        {{- false -}}

- platform: template
  sensors:
    motion_shellies_button:
      unique_id: motion_shellies_button_all
      friendly_name: Moisture
      #device_class: 'button'
      icon_template: >-
        {% if is_state('binary_sensor.motion_shellies_button','on') %}
          {{- 'mdi:water-alert' -}}
        {% else %}
          {{- 'mdi:water-outline' -}}
        {% endif %}
      value_template: >-
        {{- false -}}

- platform: template
  sensors:
    motion_shellies_heat:
      unique_id: motion_shellies_heat_all
      friendly_name: Moisture
      #device_class: 'heat'
      icon_template: >-
        {% if is_state('binary_sensor.motion_shellies_heat','on') %}
          {{- 'mdi:water-alert' -}}
        {% else %}
          {{- 'mdi:water-outline' -}}
        {% endif %}
      value_template: >-
        {{- false -}}
