###
# binary_sensor/motion/shelly.yaml
###

- platform: template
  sensors:
    motion_detector_shellies_publish:
      value_template: >-
        {% set s = states('input_boolean.motion_detector_shellies_publish') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{- s -}}
        {% else %}true{% endif %}
    motion_detector_shelly:
      friendly_name: Motion
      device_class: 'occupancy'
      availability_template: >-
        {% set s = states('sensor.motion_detector_shelly_status') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ state_attr('sensor.motion_detector_shelly_status','active')|lower != 'false' }}
        {% else %}true{% endif %}
      icon_template: >-
        {% if state_attr('sensor.motion_detector_shelly_status','motion')|lower == 'true' %}
          {{- 'mdi:motion-sensor' -}}
        {% else %}
          {{- 'mdi:motion-sensor-off' -}}
        {% endif %}
      attribute_templates:
        vibration: >-
          {{ state_attr('sensor.motion_detector_shelly_status','vibration')|lower == 'true' }}
        active: >-
          {{ state_attr('sensor.motion_detector_shelly_status','active')|lower == 'true' }}
        lux: >-
          {{ state_attr('sensor.motion_detector_shelly_status','lux') }}
        bat: >- 
          {{ state_attr('sensor.motion_detector_shelly_status','bat') }}
        id: >-
          {% set s = state_attr('binary_sensor.motion_detector_shelly','mac') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
            {% set s = states('binary_sensor.motion_detector_shelly_' + s|string) %}
            {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
              {% set s = state_attr('binary_sensor.motion_detector_shelly_' + s|string,'id') %}
              {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
                {{ s }}
              {% else %}{{- 'no id' -}}{% endif %}
            {% else %}{{- 'not found' -}}{% endif %}
          {% else %}{{- 'any' -}}{% endif %}
        timestamp: >-
          {{ state_attr('sensor.motion_detector_shelly_status','timestamp') }}
        end: >-
          {{ states('sensor.motion_detector_shelly_end') }}
        start: >-
          {{ states('sensor.motion_detector_shelly_start') }}
        duration: >-
          {{ states('sensor.motion_detector_shelly_duration') }}
        last: >-
          {{ states('sensor.motion_detector_shelly_last') }}
        when: >-
          {% set s = states('sensor.motion_detector_shelly_last') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
            {{ s|int|timestamp_custom("%a %b %d %I:%M:%S %p %Z") -}}
          {% elif is_state('binary_sensor.motion_detector_shelly','on') %}
            Now
          {% else %}
            Pending
          {% endif %}
        ago: >-
          {{ states('sensor.motion_detector_shelly_ago') }}
      value_template: >-
        {% set s = states('sensor.motion_detector_shelly_status') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {% set s = state_attr('sensor.motion_detector_shelly_status','motion') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
            {{ s|lower == 'true' }}
          {% else %}false{% endif %}
        {% else %}false{% endif %}
