###
# binary_sensor/motion/shelly.yaml
###

- platform: template
  sensors:
    motion_shellies_publish:
      value_template: >-
        {% set s = states('input_boolean.motion_shellies_publish') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{- s -}}
        {% else %}true{% endif %}
    motion_shellies_occupancy:
      friendly_name: Motion
      device_class: 'occupancy'
      availability_template: >-
        {% set s = state_attr('binary_sensor.motion_shellies_occupancy','status') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {{ s.active|lower != 'false' }}
        {% else %}true{% endif %}
      icon_template: >-
        {% set s = state_attr('binary_sensor.motion_shellies_occupancy','status') %}
        {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
          {% if s.motion|lower == 'true'  %}
            {{- 'mdi:motion-sensor' -}}
          {% else %}
            {{- 'mdi:motion-sensor-off' -}}
          {% endif %}
        {% else %}
          {{- 'mdi:progress-question' -}}
        {% endif %}
      value_template: >-
        {{- 'false' -}}
