- platform: template
  sensors:
    motion_vehicle_alpr:
      icon_template: 'mdi:car-info'
      friendly_name: Vehicle w/ ALPR
      value_template: >-
        {% if is_state('binary_sensor.motion_face_detected','on') and is_state('binary_sensor.motion_detected_person','on') %}
          {% set s = states('sensor.motion_person_faces') %}
          {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
            {% set s = s|from_json %}
            {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' and s is iterable %}
              {% set s = s|first %}
              {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' and s is iterable %}
                {% set s = s|length %}
                {% if s|lower != 'none' and s|lower != 'unavailable' and s|lower != 'unknown' and s|lower != 'null' %}
                  {{ s|int >= 1 }}
                {% else %}null{% endif %}
              {% else %}null{% endif %}
            {% else %}null{% endif %}
          {% else %}null{% endif %}
        {% else %}null{% endif %}

- platform: template
  sensors:
    motion_vehicle_alpr_expired:
      friendly_name: Vehicle w/ ALPR expired
      value_template: >-
        {{ states('sensor.motion_vehicle_alpr_ago')|int > states('input_number.motion_alpr_detected_ago')|int or
           states('sensor.motion_vehicle_alpr_ago')|int > states('input_number.motion_detected_vehicle_ago')|int }}
